### PR TITLE
fix: just disable metamods for pre420 versions

### PR DESCRIPTION
**Pull request by 0b5vr**
### Description

This patch will disable metamods options for pre420 versions.

### Points need review

- [x] Is the strategy look good enough?

### CODE REVIEW

**Review by HeySora — APPROVED** [review]
👍
I don't know how hard it is but maybe a `SCREENMAN:SystemMessage("NotITG v4.2.0 is required for metamods!")` when entering the More Options screen could be a good thing?

**Comment by ArcticFqx** [comment]
Strategy is good enough

> 👍
> I don't know how hard it is but maybe a `SCREENMAN:SystemMessage("NotITG v4.2.0 is required for metamods!")` when entering the More Options screen could be a good thing?

Wouldn't that get annoying really fast if you're on oitg?

**Review by ArcticFqx — APPROVED** [review]

**Comment by HeySora** [comment]
> Strategy is good enough
> 
> > 👍
> > I don't know how hard it is but maybe a `SCREENMAN:SystemMessage("NotITG v4.2.0 is required for metamods!")` when entering the More Options screen could be a good thing?
> 
> Wouldn't that get annoying really fast if you're on oitg?

@ArcticFqx Are there a lot of users using the "NotITG Version" on OpenITG? (genuine question)
If that's indeed the case, then showing the SystemMessage only `if FUCK_EXE then` would be a better solution: it would only warn nITG users with outdated builds.

**Comment by 0b5vr** [comment]
"bump nITG to the latest! there are so many good features!" on the title or somewhere sounds better a lot to me and should be discussed in separate I think.

**Comment by HeySora** [comment]
> "bump nITG to the latest! there are so many good features!" on the title or somewhere sounds better a lot to me and should be discussed in separate I think.

100% agreed

**Comment by ArcticFqx** [comment]
Initially, I got a request to retain oitg compatibility, but I'm not sure if that's the case anymore.
Disregarding oitg, I still think that it may be a bit annoying, no other aspects of the theme show messages if you're running an older version, it just hides the unavailable feature.

**Comment by ArcticFqx** [comment]
Nowadays it might just crash on older NotITG, not really sure.

**Comment by HeySora** [comment]
> Initially, I got a request to retain oitg compatibility, but I'm not sure if that's the case anymore.
> Disregarding oitg, I still think that it may be a bit annoying, no other aspects of the theme show messages if you're running an older version, it just hides the unavailable feature.

Keeping oITG compatibility would be great for the lua console, I just forgot about oITG users before.

**Comment by 0b5vr** [comment]
merging

**Pull request merged**
